<?php
use utils\UserIconUtil;
use utils\ParamUtil;
use utils\EncodingUtil;

/**
 * Process the form generated by details1, saving their updated account info.
 * 
 * @package Dispatchers
 */
/**
 */
function _config_editinfo()
{
    $config = Array();
    // Start config
    $config["sendWorld"] = false;
    // Stop config
    return $config;
}

function _dispatch_editinfo($template, $args, $org, $pageArgs) {

    $contactId = ParamUtil::RequiresOne($args, 'contactId');
    
    
    $contact = System::Get()->getPersonById($contactId);
    $user = SimpleSession::Get()->GetUser();
    
    $contactOrg = Organization::GetOrgByUserId($contactId);
    
    $canEditContact = ($contactId == $user->id);
    if(!$canEditContact) {
        if($pageArgs['pageActor']=='admin') {
            $canEditContact = true;
        } elseif( $contactOrg->owner->id == $user->id) {
            $canEditContact = true;
        }
    }
 
    if(!$canEditContact) {
       print javascriptalert('You do not have permission to edit this contact');
        print redirect('contact.list');
        die();
    }    
    
    $contact->realname = $_REQUEST['name'];
    $contact->email = $_REQUEST['email'];
    $contact->description = $_REQUEST['desc'];
    $contact->tags = $_REQUEST['tags'];
    $contact->phone = $_REQUEST['phone'];
    $contact->contactinfo = $_REQUEST['address'];
    $contact->visible = (isset($_REQUEST['hide']) ? false : true);
    $pwd = ParamUtil::Get($args,'password1');
    if(!is_null($pwd)) {
        if($pwd != '') { 
            $contact->password = $pwd;
        
        }
    }
    
   
    
    $doIconImport = isset($_FILES['file']);
    if($doIconImport) $doIconImport = $_FILES['file']['size'] > 0;
    
    if ($doIconImport) {
      
        
        $allowedExts = array(
            "jpg",
            "jpeg",
            "gif",
            "png"
        );
        $allowedTypes = array(
            "image/jpeg",
            "image/pjpeg",
            "image/gif",
            "image/png"
        );
        $ext = strtolower(end(explode(".", $_FILES["file"]["name"])));
        $maxFileSize = 1 * 1024 * 1024; // mega kilo byte
        
        if (in_array($ext, $allowedExts) && in_array($_FILES["file"]["type"], $allowedTypes) && $_FILES["file"]["size"] <= $maxFileSize) {
            
            
            $dir = "/mnt/userimages/user_media/" . $contact->id . '/';
            $name = "usericon.tmp." . $ext;
            
            if (! is_dir($dir))
                mkdir($dir);
            move_uploaded_file($_FILES["file"]["tmp_name"], $dir . $name);
            $contact->icon = $dir . $name;
            UserIconUtil::SetIcons($contact->id,true,$name);
            
            
            
            
           /*$img_dst = imagecreatetruecolor($w_dst, $h_dst);
            $white = imagecolorallocate($img_dst, 255, 255, 255);
            imagefilledrectangle($img_dst, 0, 0, $w_dst, $h_dst, $white);
            imagecopyresampled($img_dst, $img_src, 0, 0, 0, 0, $w_dst, $h_dst, $w_src, $h_src);
            unlink($dir . $name);
            imagejpeg($img_dst, $dir . "usericon.jpg", 100);
            */
            //imagedestroy($img_src);
            
          
        }
    }
    print redirect('contact.info&contactId=' . $contact->id);

}?>