<?php
use utils\ParamUtil;
use mail\SimpleMessage;
use mail\SimpleMail;

/**
 * Process the form generated by email1, to send the email to the targeted person.
 * 
 * @package Dispatchers
 */
/**
 */
function _config_email2()
{
    $config = Array();
    // Start config
    // Stop config
    return $config;
}

function _dispatch_email2($template, $args, $org, $pageArgs)
{
    $contactId = ParamUtil::Get($args, 'contactId');
    $target = System::Get()->getPersonById($contactId);
    
    $world = $args['world'];
    $user = $args['user'];
    
    // fetch the target person. if they don't exist, or aren't contactable by us, bail
    
    if (! $target or ! $user->canSeeUserById($contactId)) {
        print javascriptalert('Unable to locate that user.');
        return print redirect('mainmenu');
    }
    
    $subj = trim($_REQUEST['subject']);
    if(substr(strtolower($subj),0,3)=='re:') $subj = substr($subj,3);
    // make up the message hreaders, and send it off
    $from = sprintf("From: %s <%s>", $user->realname, $user->email);
    $subject = sprintf("[%s]: %s", $world->config['title'],  $subj);
    $message = "<b>From:</b> {$user->realname} ( <i>{$user->username}</i> )\n";
    $message.="<b>RE:</b> ".$subj."\n";
    $message.= ParamUtil::Get($args,'message');
    
    $simpleMessage = SimpleMessage::NewMessage($subject, $user->realname, $user->email,$message);
    $recipients = array($target->email);
    SimpleMail::SendTemplatedMessage($recipients,$simpleMessage);

    //mail($to, $subject, $message, $from);
    
    // done
    print javascriptalert('Your message has been sent.');
    print redirect("contact.info&contactId={$contactId}");
    
}
?>
