<?php
/**
 * Process the form generated by addtime1; process the credit card, add the time.
 * @package Dispatchers
 */
/**
  */
function _config_addtime2() {
	$config = Array();
	// Start config
	// Stop config
	return $config;
}

function _dispatch_addtime2($template, $args) {
$world = $args['world'];
$user = $args['user'];

// is this a free upgrade?
$free = $world->config['accountprice_'.$user->accounttype] == 0 ? true : false;

// verify that everything's in order on this end
if (!$free) {
   $error = false;
   if (!$_REQUEST['cc_cardholder']) { $error = 'You need to specify the cardholder name.'; }
   if (!$_REQUEST['cc_number'])     { $error = 'You need to enter a credit card number.'; }
   if (!$_REQUEST['Date_Year'])     { $error = 'You need to specify the expiration date for your card.'; }
   if (!$_REQUEST['Date_Month'])    { $error = 'You need to specify the expiration date for your card.'; }
   if ($error) { print javascriptalert($error); return print redirect('account.addtime1'); }
}

// calculate the price for their account type and the number of years
$price = $user->priceAddTime($_REQUEST['years']);
$description = sprintf("\$$price Account %s adding %d years to subscription", $user->username, $_REQUEST['years'] );

// run the card
/*if (!$free) {
   $result = run_creditcard($world->config['creditcardkey'],$price,$description,$_REQUEST['cc_cardholder'],$_REQUEST['cc_number'],$_REQUEST['Date_Month'],$_REQUEST['Date_Year']);
   if (!$result) {
      print javascriptalert('Your credit card did not go through. Please try again.');
      return print redirect('account.addtime1');
   }
}*/


// If we got here, the card cleared, so go ahead and add the time. If their account is
// past-expired, set their new renewal date to today so they don't get screwed out of time.
if ($user->daysUntilExpiration() < 0) { $user->expirationdate = date('Y-m-d'); }
$user->addYears($_REQUEST['years']);
$world->logAccountActivity($user->username, 'addtime', $description);

// done!
print javascriptalert('Your membership has been extended.');
print redirect('account.type');

}?>
