<?php
use utils\PageUtil;
use auth\Context;
/**
 * Process the form generated by deleteme1, to actually delete the account and then log them out.
 * @package Dispatchers
 */
/**
  */
function _config_deleteme2() {
	$config = Array();
	// Start config
	$config["sendWorld"] = false;
	// Stop config
	return $config;
}

function _dispatch_deleteme2($template, $args) {
$user = $args['user'];

$user->delete('Deleted themselves via website.');
SimpleSession::Get()->EndAllSessions($args['user']);
PageUtil::RedirectTo(Context::Get()->GetStart());
return;

}?>
