<?php
/**
 * Process the form generated by details1, saving their updated account info.
 * @package Dispatchers
 */
/**
  */
function _config_details2() {
	$config = Array();
	// Start config
	$config["sendWorld"] = false;
	// Stop config
	return $config;
}

function _dispatch_details2($template, $args) {
$user = $args['user'];

// simply set the info from the form fields, doing some sanitation
$user->visible      = (bool) $_REQUEST['visible'];
$user->email_public = (bool) @$_REQUEST['email_public'];
$user->realname     = $_REQUEST['realname'];
$user->email        = $_REQUEST['email'];
$user->description  = $_REQUEST['description'];
$user->tags     = $_REQUEST['tags'];
$user->contactinfo  = $_REQUEST['contactinfo'];

// done
print javascriptalert('Changes saved.');
print redirect('account.details1');

}?>
