<?php
/**
 * Process the form generated by defaultcolorschemesymbol1, to set the symbol for all entries.
 * @package Dispatchers
 */
/**
  */
function _config_colorschemesymbol2() {
	$config = Array();
	// Start config
	// Stop config
	return $config;
}

function _dispatch_colorschemesymbol2($template, $args) {
$world = $args['world'];
$user = $args['user'];

// load the layer and verify their access
$layer = $world->getLayerById($_REQUEST['id']);
if (!$layer or $layer->getPermissionById($user->id) < AccessLevels::EDIT) {
   print javascriptalert('You do not have permission to edit that Layer.');
   return print redirect('layer.list');
}
$template->assign('layer',$layer);

// go through the colorscheme entries for this layer, and set each one's symbol
foreach ($layer->colorscheme->getAllEntries() as $entry) {
   $entry->symbol      = $_REQUEST['symbol'];
   $entry->symbol_size = $_REQUEST['symbolsize'];
}

print redirect("default.colorscheme&id={$layer->id}");

}?>
