<?php
/**
 * Process the form generated by defaultcolorschemesetsingle1, to set the color scheme to a single-value scheme.
 * @package Dispatchers
 */
/**
  */
function _config_colorschemesetsingle2() {
	$config = Array();
	// Start config
	// Stop config
	return $config;
}

function _dispatch_colorschemesetsingle2($template, $args) {
$world = $args['world'];
$user = $args['user'];

// load the layer and verify their access
$layer = $world->getLayerById($_REQUEST['id']);
if (!$layer or $layer->getPermissionById($user->id) < AccessLevels::EDIT) {
   print javascriptalert('You do not have permission to edit that Layer.');
   return print redirect('layer.list');
}

// setting them is easy!
$layer->colorscheme->setSchemeToSingle($_REQUEST['fillcolor']);

print redirect("default.colorscheme&id={$layer->id}");

}?>
