# fonts.inc -- a set of fonts you can use with MapServer, as an alternative
# to the default bitmap font. You can add other fonts to this list, of course.
# To use these fonts, do like this:
#
# FONTSET "/maps/fonts.inc"
#    LABEL
#      TYPE truetype
#      FONT "Spiffy"
#      SIZE 8
#      POSITION AUTO
#      COLOR 0 0 0
#      OUTLINECOLOR 250 255 240
#      PARTIALS FALSE
#    END

# the Bitstream Vera fonts, courtesy of the GNOME project
Vera				Vera.ttf
VeraBoldItalic			VeraBI.ttf
VeraBold			VeraBd.ttf
VeraItalic			VeraIt.ttf
VeraMonospaceBoldItalic		VeraMoBI.ttf
VeraMonospaceBold		VeraMoBd.ttf
VeraMonospaceItalic		VeraMoIt.ttf
VeraMonospace			VeraMono.ttf
VeraSerif			VeraSe.ttf
VeraSerifBold			VeraSeBd.ttf
