<?php
/**
 * The "Search Community" subsystem -- process the form generated by demosearch, and print the list of matching projects.
 * @package Dispatchers
 */
/**
  */
function _config_searchprojects() {
	$config = Array();
	// Start config
	$config["sendUser"] = false;
	$config["authUser"] = 0;
	// Stop config
	return $config;
}

function _dispatch_searchprojects($template, $args) {
$world = $args['world'];

// fetch the matches, or lack thereof...
$searchstring = $_REQUEST['search']=='all available' ? false : $_REQUEST['search'];
$matches = array();
foreach ($world->searchProjects($searchstring) as $project) if ($project->getPermissionById($user->id)) array_push($matches,$project);
if (!$matches) { print javascriptalert('Nothing matched your search.'); return print redirect('demo.search'); }


// hand it off to the template for rendering
$template->assign('searchterm',$searchstring);
$template->assign('matches',$matches);
$template->display('demo/searchprojects.tpl');

}?>
