<?php
/**
 * The "Search Community" subsystem -- process the form generated by demosearch, and print the list of matching layers.
 * @package Dispatchers
 */
/**
  */
function _config_searchlayers() {
	$config = Array();
	// Start config
	$config["sendUser"] = false;
	$config["authUser"] = 0;
	// Stop config
	return $config;
}

function _dispatch_searchlayers($template, $args) {
$world = $args['world'];

// fetch the matches, or lack thereof...
$searchstring = $_REQUEST['search']=='all available' ? false : $_REQUEST['search'];
$matches = $world->searchLayers($searchstring);
$filtered = array_values(array_filter($matches,create_function('$a','return $a->getPermissionById(false);')));
if (!$filtered) {
   print javascriptalert('Nothing matched your search.');
   return print redirect('demo.search');
}

// hand it off to the template for rendering
$template->assign('searchterm',$searchstring);
$template->assign('matches',$filtered);
$template->display('demo/searchlayers.tpl');

}?>
