<?php
use utils\ParamUtil;
/**
 * Process the form generated by details1, saving their updated account info.
 * @package Dispatchers
 */
/**
  */
function _config_editinfo() {
	$config = Array();
	// Start config
	// Stop config
	return $config;
}

function _dispatch_editinfo($template, $args,$org,$pageArgs) {
$user = $args['user'];
$org = System::Get()->getOrganizationById($_REQUEST['id']);
if(($pageArgs['orgActor'] == 'org_owner') || ($pageArgs['pageActor']== 'admin')) {
	$updates = Array();
	$updates = ParamUtil::GetValues($_REQUEST,'name','desc:description','tags','disclaimer');
	$updates['disclaimer'] = base64_encode($updates['disclaimer']);
	if(!empty($updates)) $org->Update($updates);
}

print redirect('organization.info&orgId='.$org->id);

}?>
